CREATE TABLE CATEGORIA (
ID_CATEGORIA int NOT NULL AUTO_INCREMENT, 
NM_CATEGORIA varchar(100),
DS_CATEGORIA VARCHAR(100), 
PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE SUB_CATEGORIA (
    ID_SUB_CATEGORIA int NOT NULL AUTO_INCREMENT,
    NM_SUB_CATEGORIA varchar(100),
    DS_SUB_CATEGORIA varchar(100),
    ID_CATEGORIA int NOT NULL,
    PRIMARY KEY(ID_SUB_CATEGORIA),
    CONSTRAINT FK_ID_CATEGORIA_X_SUB FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)


);

CREATE TABLE PRODUTO (
ID_PRODUTO int NOT NULL AUTO_INCREMENT, 
NM_PRODUTO varchar(100),
DS_PRODUTO varchar(100), 
ID_CATEGORIA int,
ID_SUB_CATEGORIA int,
PRIMARY KEY (ID_PRODUTO), 
CONSTRAINT FK_ID_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
CONSTRAINT FK_ID_SUB_CAT FOREIGN KEY (ID_SUB_CATEGORIA) REFERENCES SUB_CATEGORIA(ID_SUB_CATEGORIA)
);

CREATE TABLE FORNECEDOR (
ID_FORNECEDOR int NOT NULL AUTO_INCREMENT, 
NM_FORNECEDOR varchar(100), 
CD_TP_FORNECEDOR int, 
NO_ID_FORNECEDOR int, 
PRIMARY KEY (ID_FORNECEDOR)
);

CREATE TABLE CONTATO_FORNECEDOR (
ID_CONTATO_FORNECEDOR int NOT NULL AUTO_INCREMENT,
ID_FORNECEDOR int, 
ID_TP_CONTATO int, 
DS_CONTATO_FORNECEDOR varchar(100), 
PRIMARY KEY (ID_CONTATO_FORNECEDOR), 
CONSTRAINT FK_ID_FORNECEDOR FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

CREATE TABLE TIPO_ESTOQUE (
    ID_TP_ESTOQUE int NOT NULL AUTO_INCREMENT,
    NM_TP_ESTOQUE varchar(100),
    PRIMARY KEY(ID_TP_ESTOQUE)
);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE int NOT NULL AUTO_INCREMENT,
    NM_ESTOQUE varchar(100),
    TIPO_ESTOQUE varchar(100),
    DS_ESTOQUE varchar(200),
    ID_QTD_DIVISORIA int(5),
    ID_TP_ESTOQUE int,
    PRIMARY KEY(ID_ESTOQUE),
    CONSTRAINT FK_TP_ESTOQUE_X_ESTOQUE FOREIGN KEY (ID_TP_ESTOQUE) REFERENCES TIPO_ESTOQUE(ID_TP_ESTOQUE)
);

CREATE TABLE DIVISORIA_ESTOQUE (
    ID_DIVISORIA varchar(40) NOT NULL,
    ID_ESTOQUE int NOT NULL,
    DS_DIVISORIA varchar(100),
    PRIMARY KEY (ID_DIVISORIA),
    CONSTRAINT FK_DIVISORIA_X_ESTOQUE FOREIGN KEY (ID_ESTOQUE) REFERENCES ESTOQUE(ID_ESTOQUE)
);

CREATE TABLE TP_UNIDADE_MEDIDA (
    ID_UNIDADE_MEDIDA int(5) NOT NULL AUTO_INCREMENT,
    DS_UNIDADE_MEDIDA varchar(100),
    PRIMARY KEY (ID_UNIDADE_MEDIDA)
);

CREATE TABLE CONTROLE_ENVIO (
ID_ENVIO int NOT NULL AUTO_INCREMENT, 
DS_ENVIO varchar(200), 
CD_ENVIO int, DT_ENVIO date, 
DT_ENTREGA date, ID_PRODUTO int, 
ID_CATEGORIA int, QTD_ITEM_ENVIO int, 
VALOR_TOTAL_ENVIO int, IS_TAXADO bool, 
PRIMARY KEY (ID_ENVIO), 
CONSTRAINT FK_ID_PRODUTO 
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO), 
CONSTRAINT FK_ID_CATEGORIA_too FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE CONTROLE_ESTOQUE (
ID_ITEM_ESTOQUE int NOT NULL AUTO_INCREMENT, 
ID_CATEGORIA int, 
ID_PRODUTO int, 
DS_ITEM_ESTOQUE varchar(100), 
ID_ENVIO int, 
DS_STATUS_ITEM varchar(30),
ID_DIVISORIA varchar(40),
ID_UNIDADE_MEDIDA int(5),
CD_EXCLUSAO BOOLEAN, 
DT_EXCLUSAO date, 
CD_ALTERACAO boolean, 
DT_ALTERACAO date, 
PRIMARY KEY (ID_ITEM_ESTOQUE), 
CONSTRAINT FK_ID_CATEGORIA_TT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA), 
CONSTRAINT FK_ID_PRODUTO_too FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO), 
CONSTRAINT FK_CONTROLE_ENVIO_too FOREIGN KEY (ID_ENVIO) REFERENCES controle_envio(ID_ENVIO),
CONSTRAINT FK_CONTROLE_X_DIVISORIA FOREIGN KEY (ID_DIVISORIA) REFERENCES DIVISORIA_ESTOQUE(ID_DIVISORIA),
CONSTRAINT FK_CONTROLE_X_UNIDADE FOREIGN KEY (ID_UNIDADE_MEDIDA) REFERENCES TP_UNIDADE_MEDIDA(ID_UNIDADE_MEDIDA)
);

CREATE TABLE ANEXAR_ARQUIVO_ENVIO (
ID_ARQUIVO int NOT NULL AUTO_INCREMENT, 
ID_ENVIO int, 
NM_ARQ_ENVIO varchar(100), 
CD_ARQUIVO_ENVIO varchar(100), 
PRIMARY KEY (ID_ARQUIVO), 
CONSTRAINT FK_ID_ENVIO_TT FOREIGN KEY (ID_ENVIO) REFERENCES CONTROLE_ENVIO(ID_ENVIO)
);

CREATE TABLE USUARIO (
ID_USUARIO int NOT NULL AUTO_INCREMENT, 
DS_ID_USUARIO varchar(20), 
NM_USUARIO varchar(300), 
SENHA_USUARIO varchar(100), 
EMAIL_USUARIO varchar(100), 
PRIMARY KEY (ID_USUARIO)
);


/* ------------------------------------------- Insert do Usuário Admin inicial ------------------------ */

INSERT INTO USUARIO ( DS_ID_USUARIO, NM_USUARIO, SENHA_USUARIO, EMAIL_USUARIO)
VALUES ('admin', 'Administrador', 'admin', 'gviggianofonseca@gmail.com');


/* ------------------------------------------- Insert da tabela genérica de tipo de estoque ----------- */

INSERT INTO TIPO_ESTOQUE (NM_TP_ESTOQUE)
VALUES ('Estante'),
        ('Armário'),
        ('Cômoda'),
        ('Mesa de Escritório')